### ISSUE TITLE
Version 2.1

### ISSUE THREAD

**Issue by hungluu** [CoderPush/coda-mover#11]
Version 2.1
=====

Performance drops a lot and super laggy pages with large number of docs and pages being downloaded, which calls for a simplified and more performance focused approach.

### References

- Performance drops and laggy pages: https://www.loom.com/share/a36abbeec2594090941ca5b3cd279ad7
- Updated doc for features: https://coderpush.getoutline.com/doc/versions-W3KKy77BIw#h-version-21-simplified-and-performant
- New flows' sequence digram: https://coderpush.getoutline.com/doc/versions-W3KKy77BIw#h-diagram

### User Stories

- [x] https://github.com/CoderPush/coda-mover/issues/12
- [x] https://github.com/CoderPush/coda-mover/issues/13
- [x] https://github.com/CoderPush/coda-mover/issues/17
- [x] https://github.com/CoderPush/coda-mover/issues/19
- [x] https://github.com/CoderPush/coda-mover/issues/21
- [x] #27 
- [x] #28 
- [x] #29 
- [x] #24 
- [x] #32
